# Lesson 1 Class Exercises: NumPy Part 1

In [6]:
import numpy as np

## Exercise #1

Write Python code to generate five random numbers from the normal distribution. 

Look at the online documentation for [NumPy random number generators](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html)

In [22]:

print(np.random.normal(size=5))

[ 0.48494633 -0.30330513 -2.30970856  1.06714165 -0.45261742]


## Exercise #2
Write Python code to generate six random integers between 10 and 30

Look at the online documentation for [NumPy random number generators](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html)

In [34]:
print(np.random.randint(10,31,size=6))

[23 18 21 11 10 29]


## Exercise #3
Write Python code to 
+ create a 5x5 array with random values
+ print the array,  
+ find and print the minimum and maximum values of the array. We haven't learned how to do this. See if you can find the right functions at the [NumPy API reference page](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)


In [40]:
tets=np.random.random((5,5))
print(tets)
print(np.ndarray.max(tets))
print(np.ndarray.min(tets))
print(tets.min())

[[0.05195276 0.51106109 0.70978627 0.21670919 0.78374966]
 [0.67587329 0.31099567 0.03461551 0.82382282 0.39163457]
 [0.38108943 0.0135322  0.00332632 0.77087564 0.9211655 ]
 [0.66612709 0.75095272 0.79104065 0.27662025 0.40781565]
 [0.27977558 0.98539394 0.1692366  0.19554165 0.02531148]]
0.9853939384408951
0.003326322744915622
0.003326322744915622


## Exercise #4
Write code using NumPy that would create an array that meets these criteria
+ the grid must have 30 rows and 80 columns
+ it must be initalized to zeros.
+ print the grid dimensions to prove its size.
+ print the grid to show it is initalized to zeros.

In [44]:
test=np.zeros((30,80))
print(test.shape)
print(test)

(30, 80)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Exercise #5
Read the documentation about [genfromtxt()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html) function of NumPy.  What does it do?  Do you understand what the arguments do?

A file has been provided to you named data2.txt.  Be sure to place it in the same folder with this notebook.  It contains the following text:

```
Value1,Value2,Value3 
0.4839,0.4536,0.3561 
0.1292,0.6875,NA 
0.1781,0.3049,0.8928 
NA,0.5801,0.2038 
0.5993,0.4357,0.7410
```
Notice it has missing values.  Write some code that 
+ uses the `genfromtxt` function to read in this file into a numpy array.
+ prints the resulting array.

## Exercise #6
Write some code that
+ Creates an array of 100 rows and 10 columns filled with random values between 0 and 1
+ Print the first 10 rows of the matrix (e.g. `array[0:10]`)
+ Caculate the following statistics about each row and column
  + mean, variance, standard deviation and quartiles of each row.
  + print these values.

## Exercise #7
Write code that 
+ Create an array of 100 rows and 10 columns of integer values with the minimum number 0 and the maximum 10,000
+ Print the first 10 rows of the matrix (e.g. `array[0:10]`)
+ Calculate values for a histogram with 10 bins. 
    + save in one variable the values of each bin
    + save in another variable the value at the left edge of the bin.

## Exercise #8
Write code that 

- Generates a matrix with 100 rows and 100 columns initialized with random integers between 0 and 100.
- Perform a Pearson's correlation of each row with every other row