# Lesson 2 Class Exercises: NumPy Part 2

For these exercises we will use a rather famous set of data from [iris flowers](https://en.wikipedia.org/wiki/Iris_flower_data_set).  The dataset will be provided to you.   Here's a peak at what it looks like:

```
sepal_length,sepal_width,petal_length,petal_width,species
5.1,3.5,1.4,0.2,setosa
4.9,3.0,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,1.5,0.2,setosa
5.0,3.6,1.4,0.2,setosa
```
Notice that the first 4 columns are numerical representing sepal length, sepal width, petal length and petal width. The last column is a string.  

But first, let's import Numpy.

In [53]:
import numpy as np

## Exercise 1: Data Import
Import the Iris dataset and list the dimensions of the numpy matrix after importing to ensure it's the correct size. 

Hints 
+ Use the `genfromtxt` function of NumPy
+ Remember Numpy arrays must be all of the same data type. 
+ If you give the wrong arguments you may be reading in the file as a 1D array of tuples rather than a 2D array of values.
+ This file has a header row.

In [62]:
iris= np.genfromtxt("data/iris.csv", names=True ,delimiter= ",", usecols=(0,1,2,3,4))
iris

array([(5.1, 3.5, 1.4, 0.2, nan), (4.9, 3. , 1.4, 0.2, nan),
       (4.7, 3.2, 1.3, 0.2, nan), (4.6, 3.1, 1.5, 0.2, nan),
       (5. , 3.6, 1.4, 0.2, nan), (5.4, 3.9, 1.7, 0.4, nan),
       (4.6, 3.4, 1.4, 0.3, nan), (5. , 3.4, 1.5, 0.2, nan),
       (4.4, 2.9, 1.4, 0.2, nan), (4.9, 3.1, 1.5, 0.1, nan),
       (5.4, 3.7, 1.5, 0.2, nan), (4.8, 3.4, 1.6, 0.2, nan),
       (4.8, 3. , 1.4, 0.1, nan), (4.3, 3. , 1.1, 0.1, nan),
       (5.8, 4. , 1.2, 0.2, nan), (5.7, 4.4, 1.5, 0.4, nan),
       (5.4, 3.9, 1.3, 0.4, nan), (5.1, 3.5, 1.4, 0.3, nan),
       (5.7, 3.8, 1.7, 0.3, nan), (5.1, 3.8, 1.5, 0.3, nan),
       (5.4, 3.4, 1.7, 0.2, nan), (5.1, 3.7, 1.5, 0.4, nan),
       (4.6, 3.6, 1. , 0.2, nan), (5.1, 3.3, 1.7, 0.5, nan),
       (4.8, 3.4, 1.9, 0.2, nan), (5. , 3. , 1.6, 0.2, nan),
       (5. , 3.4, 1.6, 0.4, nan), (5.2, 3.5, 1.5, 0.2, nan),
       (5.2, 3.4, 1.4, 0.2, nan), (4.7, 3.2, 1.6, 0.2, nan),
       (4.8, 3.1, 1.6, 0.2, nan), (5.4, 3.4, 1.5, 0.4, nan),
       (5.2, 4.1, 1.5, 0

## Exercise 2: Indexing & Slicing
### Task 1

Print the top 5 lines of the iris matrix.

In [ ]:
iris[:6]

array([(5.1, 3.5, 1.4, 0.2, nan), (4.9, 3. , 1.4, 0.2, nan),
       (4.7, 3.2, 1.3, 0.2, nan), (4.6, 3.1, 1.5, 0.2, nan),
       (5. , 3.6, 1.4, 0.2, nan), (5.4, 3.9, 1.7, 0.4, nan)],
      dtype=[('sepal_length', '<f8'), ('sepal_width', '<f8'), ('petal_length', '<f8'), ('petal_width', '<f8'), ('species', '<f8')])

Retrieve the first element of the first row

In [9]:
iris[0]

(5.1, 3.5, 1.4, 0.2, nan)

Retrieve the first column of the first five rows of the matrix

Retrieve the last 2 cells of the last row and the last 2 cells of the second-to-last row of the iris matrix (i.e. the 4 cells in the bottom-right corner of the matrix)

In [ ]:
[[0:6],[0]]

Identify all values in the matrix that are greater than 4 and those that are not

Retrieve all values in the matrix that are greater than 4

In [22]:
iris[iris>4]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 4.4, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8,
       5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 4.1, 5.5, 4.2, 4.9, 5. ,
       5.5, 4.9, 4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3,
       5. , 7. , 4.7, 6.4, 4.5, 6.9, 4.9, 5.5, 6.5, 4.6, 5.7, 4.5, 6.3,
       4.7, 4.9, 6.6, 4.6, 5.2, 5. , 5.9, 4.2, 6. , 6.1, 4.7, 5.6, 6.7,
       4.4, 5.6, 4.5, 5.8, 4.1, 6.2, 4.5, 5.6, 5.9, 4.8, 6.1, 6.3, 4.9,
       6.1, 4.7, 6.4, 4.3, 6.6, 4.4, 6.8, 4.8, 6.7, 5. , 6. , 4.5, 5.7,
       5.5, 5.5, 5.8, 6. , 5.1, 5.4, 4.5, 6. , 4.5, 6.7, 4.7, 6.3, 4.4,
       5.6, 4.1, 5.5, 5.5, 4.4, 6.1, 4.6, 5.8, 5. , 5.6, 4.2, 5.7, 4.2,
       5.7, 4.2, 6.2, 4.3, 5.1, 5.7, 4.1, 6.3, 6. , 5.8, 5.1, 7.1, 5.9,
       6.3, 5.6, 6.5, 5.8, 7.6, 6.6, 4.9, 4.5, 7.3, 6.3, 6.7, 5.8, 7.2,
       6.1, 6.5, 5.1, 6.4, 5.3, 6.8, 5.5, 5.7, 5. , 5.8, 5.1, 6.4, 5.3,
       6.5, 5.5, 7.7, 6.7, 7.7, 6.9, 6. , 5. , 6.9, 5.7, 5.6, 4.

### Task 3
Retrieve all rows that have at least one value greater than 4

In [31]:
iris[:,]

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

### Task 4

Write code to create a new 5 _x_ 5, 2D array that looks like the following:
```python
    [[ 1. 2. 3. 4. 5.]
     [ 1. 2. 3. 4. 5.]
     [ 1. 2. 3. 4. 5.]
     [ 1. 2. 3. 4. 5.]
     [ 1. 2. 3. 4. 5.]]
```   
Try to create this matrix using these functions:
- `np.arange()`
- `np.zero()`
- `np.reshape()`

In [42]:
matrix=np.arange(1,6)
zero=np.zeros(5).reshape(5,1)
new=matrix + zero
new

[1 2 3 4 5]


array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

Replace all elements in the array that have a value of 4 with the value 0:
```python
    [[ 1. 2. 3. 0. 5.]
     [ 1. 2. 3. 0. 5.]
     [ 1. 2. 3. 0. 5.]
     [ 1. 2. 3. 0. 5.]
     [ 1. 2. 3. 0. 5.]]
```   

In [43]:
new[new==4]=0
new

array([[1., 2., 3., 0., 5.],
       [1., 2., 3., 0., 5.],
       [1., 2., 3., 0., 5.],
       [1., 2., 3., 0., 5.],
       [1., 2., 3., 0., 5.]])

Extract the inner matrix (no border rows and columns).  Hint: you can use negative indexing.

In [44]:
new[1:-1,1:-1]

array([[2., 3., 0.],
       [2., 3., 0.],
       [2., 3., 0.]])

Write code to create a new 5 _x_ 5, 2D array with 1 on the border and 0 inside.  Without using for loops.  Output example:
```python
    [[ 1. 1. 1. 1. 1.]
     [ 1. 0. 0. 0. 1.]
     [ 1. 0. 0. 0. 1.]
     [ 1. 0. 0. 0. 1.]
     [ 1. 1. 1. 1. 1.]]
```    
Hint:
- Use the `np.ones()` function
- Use indexing

In [ ]:
np.ones()

## Exercise 3: 
Putting Things Together (NumPy Parts 1 & 2)

### Task 1
Calculate and print the mean, median and starndard deviation of the sepal length

In [59]:
print(iris[:,0].mean(),"\n")
print(np.median(iris[:,0]),"\n")
print(stdev(iris[:,0]))

5.843333333333334 

5.8 



NameError: name 'stdev' is not defined

### Task 2
Normalize the sepal length column so that all valus are between 0 and 1 such that the minimum value is 0 and the maximum is 1. Print the results.

### Task 3
Find the Pearson's correlation coefficient between sepal length and petal length.

### Task 4
Get a list of unique values from the sepal length column

### Task 5

Retrieve 5 random rows from the iris matrix

### Task 6

Retrieve 5 random values from the iris matrix and store them in a new NumPy array


## Exercise 4: Transpose

Transpose the iris array, save it into a new variable, and prints it's shape to confirm

## Exercise 5:  Resize

Use the `resize` function to expand the iris dataset to add 5 new rows, save it in a new variable. Print it's dimensions to confirm

Print the last five rows of the matrix

## Exercise 6: Putting Things Together

Fill the last 5 rows of the newly resized array with random numbers between 10 and 20, and print the last 5 rows of the matrix to confirm

## Exercise 7: Append

Use the `append` function to add five new rows of random numbers between 30 and 40. Save the new matrix in a new variable. Print the last 5 rows to confirm

## Exercise 8: Insert

Insert a row of random numbers between 40 and 50 in the second row position of the iris matrix store the value in a new variable.  Print the first 5 rows to confirm

## Exercise 9: Delete

Delete the row just added and print the first 5 rows to confirm

## Exersize 10: Putting things Together

Remove all rows where all the values in the row are greater than 2 and save in a new array. Print the shape to confirm (should loose 23 rows). Hint: this is a trick question (you wont use the `delete` function to do this).